apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fiap-aula
  template:
    metadata:
      labels:
        app: fiap-aula
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.24
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: fiap-aula
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
