apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-aula-fiap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Solicitando 1GB de disco EBS na AWS
